export { default as Main } from '../containers/Root'
export { default as Detail} from '../containers/DetailContainer'
export { default as Wish} from '../containers/WishContainer'
export { default as Watch} from '../containers/WatchContainer'
export { default as Setting} from '../containers/SettingContainer'